### ISSUE TITLE
Support for multi-character short-options

### ISSUE THREAD

**Issue by amagura** [gagle/node-argp#1]
Could you please add support for multi-char short-options?  

Example: 

``` bash
-ro, --read-only
```

**Comment by gagle** [comment]
Multi-character short options are not a GNU style. A short option by definition has only one character: http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html#Argument-Syntax

What happens if you have the options: -r, -o and -ro? You don't know if -ro is -ro or -r -o.
