### ISSUE TITLE
Expose Argp class

### ISSUE THREAD

**Issue by moll** [gagle/node-argp#3]
Hey,

I see you do a `createParser` thing in `lib/index.js`. Why not just expose Argp and let it be called with `new Argp`. Much more idiomatic JS that way.

Cheers

**Comment by gagle** [comment]
It's a common pattern in javascript to have a function that returns a new instance. `new Class()` and `Class()` do different things.

**Comment by moll** [comment]
Well, yeah, but given that all `createParser` does is return a new instance of `Argp`, why not just expose that? There's no need for the factory pattern here.

**Comment by maxtruxa** [comment]
Using a factory to expose library classes (even if it does not add anything) is perfectly fine and is much more common than exposing classes directly, especially in the node.js community.

**Comment by moll** [comment]
Umm, not exactly. Even Node.js core modules are exposed as classes.

**Comment by gagle** [comment]
@moll http://nodejs.org/api/http.html#http_http_createserver_requestlistener

**Comment by maxtruxa** [comment]
As far as I know, only the `Buffer` class and a few classes in the `Stream` module are instantiated directly. **Everything** else uses a factory.

**Comment by moll** [comment]
When you look at the implementations of `createServer` it's just as pointless as `Argp`'s. ;)
A lot of the other classes (`TLSSocket`) on `net`, `tls` etc. do not have corresponding functions.
But at least it's a function on the module with a name `createXYZ` — it's not the module itself that is a function.

If you like factories, you can just prepend an `instanceof` check at the top of the constructor like I do here, for example: https://github.com/moll/js-must/blob/master/index.js#L28.
Argp itself is OOP up to its nuts and beyond. No point in adding a factory on top of that. :-)
