### ISSUE TITLE
Calling Body.prototype.text without argument sets undefined:false in argv

### ISSUE THREAD

**Issue by moll** [gagle/node-argp#5]
Hey,

I was just trying to get some linebreaks by calling `Body.prototype.text`. Calling it without any arguments (`text()`) results in `undefined: false` being set in the `argv` object.

**Comment by moll** [comment]
Seems I was a little too trigger happy here. Not only does the `undefined` key get set when you call `text` without arguments, it also gets set when you call it with an empty string: `text("")`.

**Comment by gagle** [comment]
Ok. `text()` behaviour without an string is undefined because the string is required, but with an empty string shouldn't fail. Later I'll fix it.

**Comment by gagle** [comment]
Fixed in v1.0.4.

**Comment by moll** [comment]
:+1:

**Comment by moll** [comment]
Just noticed you missed tests for this change. ;-)

**Comment by gagle** [comment]
Help messages are not tested, only option parsing.
